
#ifdef CONSTRAINLOOP
	#define CONSTRAINA HLS_CONSTRAIN_LATENCY(0, 1, "readA_CONSTRAIN");
	#define UNROLLA HLS_UNROLL_LOOP( ON, "readA_UNROLL" );
	#define CONSTRAINCOPY HLS_CONSTRAIN_LATENCY(0, 1, "copyCtoA_CONSTRAIN");
	#define UNROLLCOPY HLS_UNROLL_LOOP( ON, "copyCtoA_UNROLL" );
	#define CONSTRAINOUT HLS_CONSTRAIN_LATENCY(0, 1, "outputC_CONSTRAIN");
	#define UNROLLOUT HLS_UNROLL_LOOP( ON, "outputC_UNROLL" );
#else
	#define CONSTRAINA
	#define UNROLLA
	#define CONSTRAINCOPY
	#define UNROLLCOPY
	#define CONSTRAINOUT
	#define UNROLLOUT
#endif
